
experiment_name: "visec_baseline_4class"

dataset:
  name: "visec"
  args:
    hf_id: "hustep-lab/ViSEC"
    batch_size: 8
    num_workers: 4
    target_size: [224, 224] # Paper Size
    spec_augment:
      freq_mask_param: 27   # Max frequency mask width (F in paper)
      time_mask_param: 30  # Max time mask width (T in paper)
      num_freq_masks: 1     # Number of frequency masks
      num_time_masks: 1     # Number of time masks
      prob: 0.5             # Probability of applying SpecAugment (50%)
    waveform_augment:
      prob: 0.6                       # Xác suất kích hoạt cả khối (Probability of Pipeline)
      pitch_shift:
        weight: 0.4                   # Trọng số 40%
        n_steps_range: [-1.0, 1.0]    # Dịch cao độ [-1.0, 1.0] semitones
      noise_injection:
        weight: 0.4                   # Trọng số 40%
        noise_factor_range: [0.001, 0.015] # Nhiễu trắng
      time_shift:
        weight: 0.2                   # Trọng số 20%
        range: [0.9, 1.1]             # Tốc độ [0.9, 1.1]

model:
  name: "maxmvit_mlp"
  type: "gmu"  # Options: original, gmu, crossattn
  num_classes: 4
  hidden_size: 512
  dropout_rate: 0.2
  # Cross-Attention specific
  num_heads: 8
  fusion_type: "concat"  # Options: concat, add, gated


training:
  epochs: 50
  lr: 0.00015 # Paper value (CRITICAL: 0.02)
  patience: 10
  seed: 42
  device: "cuda"
  scheduler:
    factor: 0.5
    patience: 5
    min_lr: 1e-6
  
paths:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
