
experiment_name: "visec_baseline_4class"

dataset:
  name: "visec"
  args:
    hf_id: "hustep-lab/ViSEC"
    batch_size: 8
    num_workers: 4
    target_size: [244, 244] # Paper Size
    p: 0.5                  # Probability of applying data augmentation (shared for all 3)
    spec_augment:
      freq_mask_param: 27   # Max frequency mask width (F in paper)
      time_mask_param: 30  # Max time mask width (T in paper)
      num_freq_masks: 1     # Number of frequency masks
      num_time_masks: 1     # Number of time masks
    pitch_shift:
      n_steps_range: [-1.0, 1.0] # Pitch shift range in semitones
    time_shift:
      range: [0.9, 1.1]     # Time stretch rate range

model:
  name: "maxmvit_mlp"
  type: "gmu"  # Options: original, gmu, crossattn
  num_classes: 4
  hidden_size: 512
  dropout_rate: 0.2
  # Cross-Attention specific
  num_heads: 8
  fusion_type: "concat"  # Options: concat, add, gated


training:
  epochs: 50
  lr: 0.00015 # Paper value (CRITICAL: 0.02)
  patience: 10
  seed: 42
  device: "cuda"
  scheduler:
    factor: 0.1
    patience: 3
    min_lr: 1e-6
  
paths:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
